articles:
  config: ./articles/config
  posts: ./articles/posts
output_dir: ./site
static_dir: ./static
author:
  name: Johnny Law
  nickname: longj
  photo: /static/img/longj_photo.png
  introduction: Study at Sun Yat-sen University, China. Major in Software Engineering. Lakers and Arsenal's fan.
  email: luojj26@mail2.sysu.edu.cn
  github: https://github.com/longjj
  zhihu: https://www.zhihu.com/people/longj-10/activities
site:
  name: Johnny Law
  description: A blog about cpp, python, and all coding skills an undergraduate have learnt.
  shortdesc: An undergraduate records his coding skills
  url: http://www.longjj.com
  title: Johnny Law's Blog Home
  keywords: 
    - linux
    - unix
    - Linux Blog
    - linux blog
    - ubuntu
    - linux os
    - Linux Server
    - bash shell
    - learning linux
    - linux operating system
    - Linux tutorials
    - Linux how to
    - cpp
    - cocos game
    - web dev
    - machine learning
special_columns:
  操作系统恐龙书阅读笔记: []