output_dir: ./site
templates_dir: ./templates
static_dir: ./static
articles:
  config: ./articles/config
  posts: ./articles/posts
author:
  name: Johnny Law
  nickname: longj
  photo: /static/img/longj_photo.png
  introduction:
    en: Major in Software Engineering at Sun Yat-sen University, China. Lakers and Arsenal's fan.
    zh: 中山大学软件工程数字媒体方向大三本科生，在个人站点上记录自己的技术发展之路，可能偶尔会写一些随笔。
  email: luojj26@mail2.sysu.edu.cn
  github: https://github.com/longjj
  zhihu: https://www.zhihu.com/people/longj-10/activities
site:
  name: Johnny Law
  description: A blog about cpp, python, and all coding skills an undergraduate have learnt.
  shortdesc: An undergraduate records his coding skills
  url: https://www.longjj.com
  title: Johnny Law's Blog Homes
  keywords:
    - linux
    - unix
    - Linux Blog
    - linux blog
    - ubuntu
    - linux os
    - Linux Server
    - bash shell
    - learning linux
    - linux operating system
    - Linux tutorials
    - Linux how to
    - cpp
    - cocos game
    - web dev
    - machine learning
    - blog
    - 博客
    - 操作系统
  notices: 
    - 鄙人在有空的时候将逐步把旧的博客迁移至这个网站里。
    - 操作系统恐龙书笔记是我的OS期末考试复习总结，记录不一定仔细齐全但重点知识点有所涵盖，有知识错漏可以邮件指正。
    - 最近在考虑是否要开一个“如何实现BeeBlog（这个站点）”的专栏(Column)。
    - 开学上课时间文章更新频率不一定保证。
special_columns:
  操作系统恐龙书阅读笔记: []