column: LeetCode Learning
description: 'leetcode 原题215解答'
file: 2017-09-24-LeetCode-kth-Largest-Element-in-an-Array.md
keywords:
  - leetcode
  - array
  - recursion
  - divide and conquer
lang: zh-cmn-Hans
post_id: 21
tags:
  - Leetcode
  - Algorithm
  - cpp
