column: LeetCode Learning
description: 'leetcode 原题133解答'
file: 2017-10-01-Leetcode-Clone-Graph.md
keywords:
  - leetcode
  - graph
  - dfs
lang: zh-cmn-Hans
post_id: 23
tags:
  - Leetcode
  - Algorithm
  - cpp