column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chpater-9--\u865A\u62DF\u5185\u5B58.md"
keywords:
- virtual memory
- 虚拟内存
lang: zh-cmn-Hans
post_id: 13
tags:
- operating system
