column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-7-\u6B7B\u9501.md"
keywords:
- dead lock
- 死锁
- 银行家算法
- 死锁避免
- 死锁检测
lang: zh-cmn-Hans
post_id: 11
tags:
- operating system
