column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-6-\u8FDB\u7A0B\u540C\u6B65.md"
keywords:
- 进程同步
- 哲学家问题
lang: zh-cmn-Hans
post_id: 10
tags:
- operating system
