column: LeetCode Learning
description: "leetcode \u539F\u989832\u89E3\u7B54"
file: 2017-12-10-LeetCode-Longest-Valid-Parentheses.md
keywords:
- leetcode
- dynamic programming
lang: zh-cmn-Hans
post_id: 36
tags:
- Leetcode
- Algorithm
- cpp
