column: LeetCode Learning
description: 'leetcode 原题53解答'
file: 2017-12-03-LeetCode-Maximum-Subarray.md
keywords:
  - leetcode
  - dynamic programming
lang: zh-cmn-Hans
post_id: 34
tags:
  - Leetcode
  - Algorithm
  - cpp
