column: LeetCode Learning
description: 'leetcode 原题101解答'
file: 2017-10-08-Leetcode-Symmetric-Tree.md
keywords:
  - leetcode
  - binary tree
  - recursion
lang: zh-cmn-Hans
post_id: 24
tags:
  - Leetcode
  - Algorithm
  - cpp