column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-5-CPU\u8C03\u5EA6.md"
keywords:
- CPU
- CPU调度
- 分时
lang: zh-cmn-Hans
post_id: 9
tags:
- operating system
