column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-10-\u6587\u4EF6\u7CFB\u7EDF\u63A5\u53E3.md"
keywords:
- File system
- interface
- 文件系统接口
lang: zh-cmn-Hans
post_id: 14
tags:
- operating system
