column: LeetCode Learning
description: 'leetcode 原题169解答'
file: 2017-09-24-LeetCode-Majority-Element.md
keywords:
  - leetcode
  - array
lang: zh-cmn-Hans
post_id: 22
tags:
  - LeetCode
  - Algorithm
  - cpp
