column: LeetCode Learning
description: 'leetcode 原题198解答'
file: 2017-12-24-LeetCode-House-Robber.md
keywords:
  - leetcode
  - dynamic programming
post_id: 43
lang: zh-cmn-Hans
tags:
  - Leetcode
  - Algorithm
  - cpp
