column: LeetCode Learning
description: 'leetcode 原题99解答'
file: 2017-10-29-Leetcode-Recover-Binary-Search-Tree.md
keywords:
  - leetcode
  - binary tree
  - inorder
  - Morris Traversal
  - BST
lang: zh-cmn-Hans
post_id: 28
tags:
  - Leetcode
  - Algorithm
  - cpp