column: LeetCode Learning
description: 'leetcode 原题100解答'
file: 2017-10-15-LeetCode-Same-Tree.md
keywords:
  - leetcode
  - binary tree
  - dfs
lang: zh-cmn-Hans
post_id: 26
tags:
  - Leetcode
  - Algorithm
  - cpp