column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-8-\u5185\u5B58\u7BA1\u7406.md"
keywords:
- Memory
- Memory manager
- 内存管理
lang: zh-cmn-Hans
post_id: 12
tags:
- operating system
