column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-13-IO\u8F93\u5165\u7CFB\u7EDF.md"
keywords:
- I/O
- computer input and output
lang: zh-cmn-Hans
post_id: 17
tags:
- operating system
