column: LeetCode Learning
description: 'leetcode 原题152解答'
file: 2017-12-24-LeetCode-Maximum-Product-Subarray.md
keywords:
  - leetcode
  - dynamic programming
post_id: 44
tags:
  - Leetcode
  - Algorithm
  - cpp
