description: 恐龙书阅读笔记，第二章操作系统结构的自我总结
post_id: 6
tags:
- operating system
file: 2017-08-22-osnote-Chapter-2-Operating-System-Structure.md
keywords:
- operating system structure
lang: zh-cmn-Hans
column: 操作系统恐龙书阅读笔记