column: LeetCode Learning
description: 'leetcode 原题96解答'
file: 2017-12-17-LeetCode-Unique-Binary-Search-Trees.md
keywords:
  - leetcode
  - dynamic programming
lang: zh-cmn-Hans
post_id: 40
tags:
  - Leetcode
  - Algorithm
  - cpp
