column: How to Build Your Own Blog
description: 'Why we need to build our own blog?'
file: "2017-09-09-\u81EA\u5DF1\u642D\u5EFA\u4E00\u4E2ABlog\u5427.md"
keywords:
  - blog
  - static site generator
lang: 'zh-cmn-Hans'
post_id: 19
tags:
  - 观点
