column: "\u64CD\u4F5C\u7CFB\u7EDF\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
description: "\u6050\u9F99\u4E66\u9605\u8BFB\u7B14\u8BB0"
file: "2017-08-27-Chapter-4-\u7EBF\u7A0B.md"
keywords:
- 线程
- thread
lang: zh-cmn-Hans
post_id: 8
tags:
- operating system
