column: "\u7CFB\u7EDF\u5206\u6790\u4E0E\u8BBE\u8BA1\u8BFE\u7A0B\u4F5C\u4E1A\u63D0\u4EA4"
description: '软件生命周期以及一些相关模型'
file: 2018-03-20-Systems-Analysis-and-Design-hw2.md
keywords:
  - 软件工程
  - SDLS
  - 软件生命周期
  - 瀑布模型
  - 原型模型
  - UP
  - RUP
lang: zh-cmn-Hans
post_id: 48
tags:
  - 软件工程
