column: "\u7CFB\u7EDF\u5206\u6790\u4E0E\u8BBE\u8BA1\u8BFE\u7A0B\u4F5C\u4E1A\u63D0\u4EA4"
description: '用例建模和业务建模相关'
file: 2018-04-22-Systems-Analysis-and-Design-hw3.md
keywords:
  - Use Case
lang: zh-cmn-Hans
post_id: 50
release_time: '2018-04-22T21:12:30.240922'
tags:
  - 软件工程
