column: "\u7CFB\u7EDF\u5206\u6790\u4E0E\u8BBE\u8BA1\u8BFE\u7A0B\u4F5C\u4E1A\u63D0\u4EA4"
description: '软件工程的一些基本概念'
file: "2018-03-13-\u7CFB\u7EDF\u5206\u6790\u4E0E\u8BBE\u8BA1-Homework-1.md"
keywords:
  - 软件工程
  - SWEBok
  - PSP
lang: zh-cmn-Hans
post_id: 47
tags:
  - 软件工程
